USE Spring_2018_Baseball
GO

CREATE VIEW mer4_Player_History
	(PlayerID, Player_Name, NumTeams, NumYears, Tot_Salary, Avg_Salary, Last_college, 
		Last_College_Year, Num_College_Years, NumColleges, Year_last_played, 
			Last_Team_played_for, Last_Year_in_AllStars, Last_teamID_in_AllStars, 
				Last_Team_in_AllStars, Last_Lg_in_AllStars, Last_Position_in_AllStars, 
					Year_highest_BatAvg, Highest_BatAvg, Team_of_Highest_BatAvg, Total_Home_runs, 
						Years_as_Manager, Num_Teams_Managed, Avg_pcent_wins_as_manager, 
							Year_of_highest_pcent_wins, Team_of_highest_pcent_wins)
								AS 
									WITH Player_data AS (SELECT m.playerID, 
												(m.nameFirst + ' (' + m.nameGiven + ') ' + m.nameLast) AS playerName,
															(SELECT COUNT(*) FROM (SELECT playerID, teamID
																		FROM Appearances 
																					GROUP BY playerID, teamID) a 
																								WHERE m.playerID = a.playerID) AS #_of_Teams_played_for,
																											(SELECT MAX(yearID) - MIN(yearID) + 1 
																														FROM Appearances a	
																																	WHERE m.playerID = a.playerID) AS #_of_Yrs_played_for
																																				FROM Master m), 
																																						Salary_data AS (SELECT DISTINCT s.playerID, SUM(s.salary) AS Total_salary, 
																																									AVG(s.salary) AS Avg_salary
																																												FROM Salaries s
																																															GROUP BY playerID),
																																																	College_data AS (SELECT DISTINCT c.playerID, s.name_full AS Last_College, 
																																																				cc.Yr_Last_played_in_College, cc.#_of_Yrs_played_for, 
																																																							(SELECT COUNT(*) 
																																																										FROM (SELECT playerID, schoolID
																																																													FROM CollegePlaying
																																																																GROUP BY playerID, schoolID) x
																																																																			WHERE cc.playerID = x.playerID) AS #_of_Colleges_played_for
																																																																						FROM CollegePlaying c, 
																																																																									(SELECT c.playerID, MAX(c.yearID) AS Yr_Last_played_in_College,
																																																																												(MAX(c.yearID) - MIN(c.yearID) + 1) AS #_of_Yrs_played_for
																																																																															FROM CollegePlaying c
																																																																																		GROUP BY playerID) cc, Schools s
																																																																																					WHERE c.playerID = cc.playerID and s.schoolID = c.schoolID and 
																																																																																										c.yearID = cc.Yr_Last_played_in_College),
																																																																																												Career_data AS (SELECT DISTINCT a.playerID, aa.Yr_Last_played, t.name 
																																																																																															FROM Appearances a, 
																																																																																																		(SELECT a.playerID, MAX(a.yearID) AS Yr_Last_played
																																																																																																					FROM Appearances a	
																																																																																																								GROUP BY a.playerID) aa, Teams t
																																																																																																											WHERE a.playerID = aa.playerID and a.teamID = t.teamID and
																																																																																																															a.yearID = t.yearID and a.lgID = t.lgID and a.yearID = aa.Yr_Last_played),
																																																																																																																	AllStar_data AS (SELECT DISTINCT a.playerID, a.yearID, 
																																																																																																																				a.teamID AS Last_AllStars_TeamID, 
																																																																																																																							t.name AS Last_AllStars_Team_name,
																																																																																																																										a.lgID AS Last_AllStars_lgID,
																																																																																																																													a.startingPos AS Last_AllStars_Pos
																																																																																																																																FROM AllstarFull a, 
																																																																																																																																			(SELECT a.playerID, MAX(a.yearID) AS Last_Yr_played_in_AllStars
																																																																																																																																						FROM AllstarFull a
																																																																																																																																									GROUP BY playerID) aa, Teams t
																																																																																																																																												WHERE a.playerID = aa.playerID and t.teamID = a.teamID and
																																																																																																																																																t.yearID = a.yearID and t.lgID = a.lgID and
																																																																																																																																																				a.yearID = aa.Last_Yr_played_in_AllStars),
																																																																																																																																																						Batting_data AS (SELECT DISTINCT b.playerID, b.yearID AS Highest_Bat_Avg_Yr, 
																																																																																																																																																									b.Bat_Avg AS Highest_Bat_Avg, b.teamID AS Highest_Bat_Avg_Team, 
																																																																																																																																																												bb.Total_Home_Run
																																																																																																																																																															FROM (SELECT *, H*1.0/AB AS Bat_Avg 
																																																																																																																																																																		FROM Batting 
																																																																																																																																																																					WHERE AB > 0) b, (SELECT bx.playerID, MAX(bx.Bat_Avg) AS Highest_bat_Avg,
																																																																																																																																																																								SUM(bx.HR) AS Total_Home_Run
																																																																																																																																																																											FROM (SELECT *, H*1.0/AB AS Bat_Avg 
																																																																																																																																																																														FROM Batting 
																																																																																																																																																																																	WHERE AB > 0) bx
																																																																																																																																																																																				GROUP BY bx.playerID) bb, Teams t
																																																																																																																																																																																							WHERE b.playerID = bb.playerID and b.Bat_Avg = bb.Highest_bat_Avg and
																																																																																																																																																																																											b.teamID = t.teamID and b.yearID = t.yearID and b.lgID = t.lgID),
																																																																																																																																																																																													Manager_data AS (SELECT DISTINCT m1.playerID, mx.#_of_Years_as_Mgr,
																																																																																																																																																																																																(SELECT COUNT(*)
																																																																																																																																																																																																			FROM (SELECT playerID, teamID 
																																																																																																																																																																																																						FROM Managers
																																																																																																																																																																																																									WHERE plyrMgr = 'Y'
																																																																																																																																																																																																												GROUP BY playerID, teamID) m2
																																																																																																																																																																																																															WHERE m1.playerID = m2.playerID) AS #_of_teams_managed,
																																																																																																																																																																																																																		FORMAT(mx.Avg_WR,'P') AS Average_Win_Percent,
																																																																																																																																																																																																																					m1.yearID AS Max_Mgr_win_percent_year,
																																																																																																																																																																																																																								t.name AS Max_Mgr_win_percent_team
																																																																																																																																																																																																																											FROM Teams t, (SELECT *,(W*1.0/G) AS Win_ratio 
																																																																																																																																																																																																																														FROM Managers 
																																																																																																																																																																																																																																	WHERE plyrMgr = 'Y') m1, (Select playerID, 
																																																																																																																																																																																																																																				MAX(yearID) - MIN(yearID) + 1 AS #_of_Years_as_Mgr,
																																																																																																																																																																																																																																							AVG(Win_ratio) AS Avg_WR, 
																																																																																																																																																																																																																																										MAX(Win_ratio) AS Max_WR 
																																																																																																																																																																																																																																													FROM (SELECT *,(W*1.0/G) AS Win_ratio 
																																																																																																																																																																																																																																																FROM Managers 
																																																																																																																																																																																																																																																			WHERE plyrMgr = 'Y') mm
																																																																																																																																																																																																																																																						GROUP BY playerID) mx
																																																																																																																																																																																																																																																									WHERE m1.playerID = mx.playerID and m1.yearID = t.yearID and
																																																																																																																																																																																																																																																													m1.teamID = t.teamID and m1.lgID = t.lgID and m1.Win_ratio = mx.Max_WR)
																																																																																																																																																																																																																																																																(SELECT pd.playerID, pd.playerName, pd.#_of_Teams_played_for, 
																																																																																																																																																																																																																																																																				pd.#_of_Yrs_played_for, sd.Total_salary, sd.Avg_salary, cd.Last_College, 
																																																																																																																																																																																																																																																																								cd.Yr_Last_played_in_College, cd.#_of_Yrs_played_for, 
																																																																																																																																																																																																																																																																												cd.#_of_Colleges_played_for, cad.Yr_Last_played, cad.name, ad.yearID, 
																																																																																																																																																																																																																																																																																ad.Last_AllStars_TeamID, ad.Last_AllStars_Team_name, ad.Last_AllStars_lgID, 
																																																																																																																																																																																																																																																																																				ad.Last_AllStars_Pos, bd.Highest_Bat_Avg_Yr,
																																																																																																																																																																																																																																																																																								bd.Highest_Bat_Avg, bd.Highest_Bat_Avg_Team, bd.Total_Home_Run,
																																																																																																																																																																																																																																																																																												md.#_of_Years_as_Mgr, md.#_of_teams_managed, md.Average_Win_Percent,
																																																																																																																																																																																																																																																																																																md.Max_Mgr_win_percent_year, md.Max_Mgr_win_percent_team
																																																																																																																																																																																																																																																																																																			FROM Player_data pd left outer join Salary_data sd ON pd.playerID = sd.playerID 
																																																																																																																																																																																																																																																																																																									left outer join College_data cd ON pd.playerID = cd.playerID
																																																																																																																																																																																																																																																																																																															left outer join Career_data cad ON pd.playerID = cad.playerID
																																																																																																																																																																																																																																																																																																																					left outer join AllStar_data ad ON pd.playerID = ad.playerID
																																																																																																																																																																																																																																																																																																																											left outer join Batting_data bd ON pd.playerID = bd.playerID
																																																																																																																																																																																																																																																																																																																																	left outer join Manager_data md ON pd.playerID = md.playerID)
																																																																																																																																																																																																																																																																																																																																		GO

																																																																																																																																																																																																																																																																																																																																		SELECT * FROM mer4_Player_History
																																																																																																																																																																																																																																																																																																																																		GO

																																																																																																																																																																																																																																																																																																																																		/*
																																																																																																																																																																																																																																																																																																																																		with batting_average(playerid, Max_year, batting_avg) as 
																																																																																																																																																																																																																																																																																																																																		(select batting.playerid, batting_avg, max(yearid) as Max_Year
																																																																																																																																																																																																																																																																																																																																			from batting, (select playerid, max((batting.h*1.00/batting.ab)) as batting_avg from Batting 
																																																																																																																																																																																																																																																																																																																																				where batting.ab> 0 and batting.stint = 1 
																																																																																																																																																																																																																																																																																																																																					group by playerid) a
																																																																																																																																																																																																																																																																																																																																						where batting.playerid = a.playerid and 
																																																																																																																																																																																																																																																																																																																																							batting.h*1.00/batting.ab = batting_avg
																																																																																																																																																																																																																																																																																																																																								and batting.ab > 0
																																																																																																																																																																																																																																																																																																																																									group by batting.playerid, batting_avg),
																																																																																																																																																																																																																																																																																																																																									Total_HR(playerid,Tot_hr) as
																																																																																																																																																																																																																																																																																																																																										(select playerid, sum(hr)
																																																																																																																																																																																																																																																																																																																																												from Batting
																																																																																																																																																																																																																																																																																																																																														group by playerid)
																																																																																																																																																																																																																																																																																																																																														select batting_average.playerid, max_year, batting_avg, tot_hr
																																																																																																																																																																																																																																																																																																																																															from batting_average, total_HR
																																																																																																																																																																																																																																																																																																																																																where batting_average.playerid = total_hr.playerid
																																																																																																																																																																																																																																																																																																																																																	order by batting_average.playerid

																																																																																																																																																																																																																																																																																																																																																	go

																																																																																																																																																																																																																																																																																																																																																	with batting_average(playerid, Max_year, batting_avg) as 
																																																																																																																																																																																																																																																																																																																																																	(select batting.playerid, batting_avg, max(yearid) as Max_Year
																																																																																																																																																																																																																																																																																																																																																		from batting, (select playerid, max((batting.h*1.00/batting.ab)) as batting_avg from Batting 
																																																																																																																																																																																																																																																																																																																																																			where batting.ab> 0 and batting.stint = 1 
																																																																																																																																																																																																																																																																																																																																																				group by playerid) a
																																																																																																																																																																																																																																																																																																																																																					where batting.playerid = a.playerid and 
																																																																																																																																																																																																																																																																																																																																																						batting.h*1.00/batting.ab = batting_avg
																																																																																																																																																																																																																																																																																																																																																							and batting.ab > 0
																																																																																																																																																																																																																																																																																																																																																								group by batting.playerid, batting_avg),
																																																																																																																																																																																																																																																																																																																																																								Total_HR(playerid,Tot_hr) as
																																																																																																																																																																																																																																																																																																																																																									(select playerid, sum(hr)
																																																																																																																																																																																																																																																																																																																																																											from Batting
																																																																																																																																																																																																																																																																																																																																																													group by playerid)
																																																																																																																																																																																																																																																																																																																																																													select master.playerid, nameLast+ ', ' + nameFirst as Full_Name, max_year, batting_avg, tot_hr
																																																																																																																																																																																																																																																																																																																																																														from master, batting_average, total_HR
																																																																																																																																																																																																																																																																																																																																																															where master.playerid = batting_average.playerid and
																																																																																																																																																																																																																																																																																																																																																																		batting_average.playerid = total_hr.playerid
																																																																																																																																																																																																																																																																																																																																																																			order by batting_average.playerid
																																																																																																																																																																																																																																																																																																																																																																			go

																																																																																																																																																																																																																																																																																																																																																																			with batting_average(playerid, Max_year, batting_avg) as 
																																																																																																																																																																																																																																																																																																																																																																			(select batting.playerid, batting_avg, max(yearid) as Max_Year
																																																																																																																																																																																																																																																																																																																																																																				from batting, (select playerid, max((batting.h*1.00/batting.ab)) as batting_avg from Batting 
																																																																																																																																																																																																																																																																																																																																																																					where batting.ab> 0 and batting.stint = 1 
																																																																																																																																																																																																																																																																																																																																																																						group by playerid) a
																																																																																																																																																																																																																																																																																																																																																																							where batting.playerid = a.playerid and 
																																																																																																																																																																																																																																																																																																																																																																								batting.h*1.00/batting.ab = batting_avg
																																																																																																																																																																																																																																																																																																																																																																									and batting.ab > 0
																																																																																																																																																																																																																																																																																																																																																																										group by batting.playerid, batting_avg)
																																																																																																																																																																																																																																																																																																																																																																										select count(*) from batting_average

																																																																																																																																																																																																																																																																																																																																																																										go
																																																																																																																																																																																																																																																																																																																																																																										WITH Total_HR(playerid,Tot_hr) as
																																																																																																																																																																																																																																																																																																																																																																											(select playerid, sum(hr)
																																																																																																																																																																																																																																																																																																																																																																													from Batting
																																																																																																																																																																																																																																																																																																																																																																															group by playerid)
																																																																																																																																																																																																																																																																																																																																																																															select count(*) from Total_HR

																																																																																																																																																																																																																																																																																																																																																																															go

																																																																																																																																																																																																																																																																																																																																																																															select count(*) from master

																																																																																																																																																																																																																																																																																																																																																																															go


																																																																																																																																																																																																																																																																																																																																																																															with batting_average(playerid, Max_year, batting_avg) as 
																																																																																																																																																																																																																																																																																																																																																																															(select batting.playerid, batting_avg, max(yearid) as Max_Year
																																																																																																																																																																																																																																																																																																																																																																																from batting, (select playerid, max((batting.h*1.00/batting.ab)) as batting_avg from Batting 
																																																																																																																																																																																																																																																																																																																																																																																	where batting.ab> 0 and batting.stint = 1 
																																																																																																																																																																																																																																																																																																																																																																																		group by playerid) a
																																																																																																																																																																																																																																																																																																																																																																																			where batting.playerid = a.playerid and 
																																																																																																																																																																																																																																																																																																																																																																																				batting.h*1.00/batting.ab = batting_avg
																																																																																																																																																																																																																																																																																																																																																																																					and batting.ab > 0
																																																																																																																																																																																																																																																																																																																																																																																						group by batting.playerid, batting_avg),
																																																																																																																																																																																																																																																																																																																																																																																						Total_HR(playerid,Tot_hr) as
																																																																																																																																																																																																																																																																																																																																																																																							(select playerid, sum(hr)
																																																																																																																																																																																																																																																																																																																																																																																									from Batting
																																																																																																																																																																																																																																																																																																																																																																																											group by playerid)
																																																																																																																																																																																																																																																																																																																																																																																											select master.playerid, nameLast+ ', ' + nameFirst as Full_Name, max_year, batting_avg, tot_hr
																																																																																																																																																																																																																																																																																																																																																																																												from master LEFT JOIN batting_average on master.playerid = batting_average.playerid
																																																																																																																																																																																																																																																																																																																																																																																																LeFT JOIN Total_HR on master.playerid = total_HR.playerid
																																																																																																																																																																																																																																																																																																																																																																																																	order by master.playerid

																																																																																																																																																																																																																																																																																																																																																																																																	select * from batting where playerid = 'abbotgl01'

																																																																																																																																																																																																																																																																																																																																																																																																	DROP VIEW mer4_Player_History
																																																																																																																																																																																																																																																																																																																																																																																																	*/
